development:
  adapter: postgresql
  encoding: unicode
  database: online_quiz_development
  pool: 5
  username: postgres
  password: 123456
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: online_quiz_test
  pool: 5
  username: postgres
  password: 123456
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: online_quiz_production
  pool: 5
  username: postgres
  password: 123456
  host: localhost
